### PR TITLE
Add spinner styles and variables

### PR DESCRIPTION
**Pull request by jorjordandan**
I'm porting the ionic spinner to meteoric, but it will need the styles...

### CODE REVIEW

**Comment by jorjordandan** [comment]
Not sure what the github etiquette is around version bumping, but it would be nice if I could update this meteor package and use the styles. Should I have included a version bump in the package.js or would have been the wrong thing to do?

**Comment by nickw** [comment]
Hi @jorjordandan for the sass packages I think we want to keep a 1:1 mapping between the official ionic lib. So ideally we'd pull in all the files from the latest ionic version and bump our version number to match.

**Comment by jorjordandan** [comment]
Ah okay! Thanks, I'll do that.

**Comment by nickw** [comment]
Closing this in lieu of importing the entire scss lib.

**Comment by jorjordandan** [comment]
The last 2 commits import the latest library and bumps the version, The only difference is that I removed the ion icons import because that's in a different package.

**Pull request closed without merging**
